sonar.projectKey=devashishcodes_Boardgame
sonar.organization=devashishcodes
sonar.projectName=Boardgame
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
